services:

    _defaults:
        # Automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        autowire: true
               
    lemisoft.sylius_abandoned_cart_plugin.command.abandoned_cart_remove_command:
        class: Lemisoft\SyliusAbandonedCartPlugin\Command\AbandonedCartRemoveCommand
        arguments:
            - '@lemisoft.sylius_abandoned_cart_plugin.service.abandoned_cart.service'
        tags:
            - { name: console.command }            
