sylius_ui:
    events:
        sylius.admin.abandoned_cart.show.content:
            blocks:
                before_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 35
                    context:
                        event: sylius.admin.abandoned_cart.show.before_header
                header:
                    template: "@LemisoftSyliusAbandonedCartPlugin/Admin/AbandonedCart/Show/_headerWidget.html.twig"
                    priority: 30
                after_header_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 25
                    context:
                        event: sylius.admin.abandoned_cart.show.after_header
                breadcrumb:
                    template: "@SyliusAdmin/Order/Show/_breadcrumb.html.twig"
                    priority: 20
                after_breadcrumb_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: sylius.admin.abandoned_cart.show.after_breadcrumb
                content:
                    template: "@LemisoftSyliusAbandonedCartPlugin/Admin/AbandonedCart/Show/_content.html.twig"
                    priority: 10
                after_content_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.admin.abandoned_cart.show.after_content
        sylius.admin.abandoned_cart.show.sidebar:
            blocks:
                before_customer_information_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 55
                    context:
                        event: sylius.admin.abandoned_cart.show.before_customer_information
                customer:
                    template: "@LemisoftSyliusAbandonedCartPlugin/Admin/AbandonedCart/Show/_customer.html.twig"
                    priority: 50
                before_addresses_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 45
                    context:
                        event: sylius.admin.abandoned_cart.show.before_addresses
                addresses:
                    template: "@SyliusAdmin/Order/Show/_addresses.html.twig"
                    priority: 40
                before_payments_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 35
                    context:
                        event: sylius.admin.abandoned_cart.show.before_payments
                payments:
                    template: "@LemisoftSyliusAbandonedCartPlugin/Admin/AbandonedCart/Show/_payments.html.twig"
                    priority: 30
                shipments:
                    template: "@LemisoftSyliusAbandonedCartPlugin/Admin/AbandonedCart/Show/_shipments.html.twig"
                    priority: 20
                after_shipments_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.admin.abandoned_cart.show.after_shipments
