lemisoft_sylius_abandoned_cart_index:
    path: /abandoned-carts
    methods: [ GET ]
    defaults:
        _controller: sylius.controller.order::indexAction
        _sylius:
            grid: lemisoft_sylius_abandoned_cart_admin
            section: "admin"
            permission: true
            template: "@SyliusAdmin/Crud/index.html.twig"

lemisoft_sylius_abandoned_cart_delete:
    path: /orders/{id}/remove
    methods: [ DELETE ]
    defaults:
        _controller: sylius.controller.order::deleteAction
        _sylius:
            repository:
                method: getAbandonedCart
                arguments:
                    - '!!int $id'
                    - '!!int %hours_to_abandoned_cart%'
            section: admin
            permission: true
            redirect:
                route: lemisoft_sylius_abandoned_cart_index

lemisoft_sylius_abandoned_cart_show:
    path: /abandoned-carts/{id}
    methods: [ GET ]
    defaults:
        _controller: sylius.controller.order::showAction
        _sylius:
            repository:
                method: getAbandonedCart
                arguments:
                    - '!!int $id'
                    - '!!int %hours_to_abandoned_cart%'
            section: admin
            permission: true
            template: "@LemisoftSyliusAbandonedCartPlugin/Admin/AbandonedCart/show.html.twig"
